import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

const CONTRACT_NAME = "Donation";
const rel = "../backend";
const outdir = path.resolve("./abi");
if (!fs.existsSync(outdir)) fs.mkdirSync(outdir);

const dir = path.resolve(rel);
const dirname = path.basename(dir);
const line = "\n===================================================================\n";

if (!fs.existsSync(dir)) {
  console.error(`${line}Unable to locate ${rel}. Expecting packages/${dirname}${line}`);
  process.exit(1);
}

const deploymentsDir = path.join(dir, "deployments");

function deployOnHardhatNode() {
  if (process.platform === "win32") return; // skip on Windows
  try {
    execSync(`./deploy-hardhat-node.sh`, { cwd: path.resolve("./scripts"), stdio: "inherit" });
  } catch (e) {
    console.error(`${line}Script execution failed: ${e}${line}`);
    process.exit(1);
  }
}

function readDeployment(chainName, chainId, contractName, optional) {
  const chainDeploymentDir = path.join(deploymentsDir, chainName);
  if (!fs.existsSync(chainDeploymentDir) && chainId === 31337) {
    deployOnHardhatNode();
  }
  if (!fs.existsSync(chainDeploymentDir)) {
    console.error(`${line}Unable to locate '${chainDeploymentDir}' directory.\n\n1. Goto '${dirname}' directory\n2. Run 'npx hardhat deploy --network ${chainName}'.${line}`);
    if (!optional) process.exit(1);
    return undefined;
  }
  const jsonString = fs.readFileSync(path.join(chainDeploymentDir, `${contractName}.json`), "utf-8");
  const obj = JSON.parse(jsonString);
  obj.chainId = chainId;
  return obj;
}

function readAbiFromArtifacts(contractName) {
  const artifactsJsonPath = path.join(dir, "artifacts", "contracts", `${contractName}.sol`, `${contractName}.json`);
  if (!fs.existsSync(artifactsJsonPath)) {
    console.error(`${line}Unable to locate artifacts at '${artifactsJsonPath}'.\n\n1. Goto '${dirname}' directory\n2. Run 'npm run compile'.${line}`);
    process.exit(1);
  }
  const jsonString = fs.readFileSync(artifactsJsonPath, "utf-8");
  const obj = JSON.parse(jsonString);
  return { abi: obj.abi, address: "0x0000000000000000000000000000000000000000", chainId: 31337 };
}

let deployLocalhost = readDeployment("localhost", 31337, CONTRACT_NAME, true);
if (!deployLocalhost) {
  deployLocalhost = readAbiFromArtifacts(CONTRACT_NAME);
}
let deploySepolia = readDeployment("sepolia", 11155111, CONTRACT_NAME, true);
if (!deploySepolia) {
  deploySepolia = { abi: deployLocalhost.abi, address: "0x0000000000000000000000000000000000000000" };
}
if (deployLocalhost && deploySepolia) {
  if (JSON.stringify(deployLocalhost.abi) !== JSON.stringify(deploySepolia.abi)) {
    console.error(`${line}Deployments on localhost and Sepolia differ. Cannot use the same abi. Re-deploy.${line}`);
    process.exit(1);
  }
}

const tsCode = `
/* Auto-generated by 'npm run genabi' */
export const ${CONTRACT_NAME}ABI = ${JSON.stringify({ abi: deployLocalhost.abi }, null, 2)} as const;
`;
const tsAddresses = `
/* Auto-generated by 'npm run genabi' */
export const ${CONTRACT_NAME}Addresses = {
  "11155111": { address: "${deploySepolia.address}", chainId: 11155111, chainName: "sepolia" },
  "31337": { address: "${deployLocalhost.address}", chainId: 31337, chainName: "hardhat" }
};
`;

fs.writeFileSync(path.join(outdir, `${CONTRACT_NAME}ABI.ts`), tsCode, "utf-8");
fs.writeFileSync(path.join(outdir, `${CONTRACT_NAME}Addresses.ts`), tsAddresses, "utf-8");
console.log(`Generated ${path.join(outdir, `${CONTRACT_NAME}ABI.ts`)}`);
console.log(`Generated ${path.join(outdir, `${CONTRACT_NAME}Addresses.ts`)}`);


