
/* Auto-generated by 'npm run genabi' */
export const DonationAddresses = {
  "11155111": { address: "0xb806bD87fF6070618B5b629C5E2dfA0459fc2129", chainId: 11155111, chainName: "sepolia" },
  "31337": { address: "0x0000000000000000000000000000000000000000", chainId: 31337, chainName: "hardhat" }
};
