/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DonationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "createProject"
      | "donate"
      | "getDonationOf"
      | "getMyDonation"
      | "getProjectCount"
      | "getProjectInfo"
      | "getProjectTotal"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Donated" | "ProjectCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonationOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyDonation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectTotal",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDonationOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectTotal",
    data: BytesLike
  ): Result;
}

export namespace DonatedEvent {
  export type InputTuple = [projectId: BigNumberish, donor: AddressLike];
  export type OutputTuple = [projectId: bigint, donor: string];
  export interface OutputObject {
    projectId: bigint;
    donor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    owner: AddressLike,
    name: string
  ];
  export type OutputTuple = [projectId: bigint, owner: string, name: string];
  export interface OutputObject {
    projectId: bigint;
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Donation extends BaseContract {
  connect(runner?: ContractRunner | null): Donation;
  waitForDeployment(): Promise<this>;

  interface: DonationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createProject: TypedContractMethod<[name: string], [bigint], "nonpayable">;

  donate: TypedContractMethod<
    [projectId: BigNumberish, inputAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getDonationOf: TypedContractMethod<
    [projectId: BigNumberish, donor: AddressLike],
    [string],
    "view"
  >;

  getMyDonation: TypedContractMethod<
    [projectId: BigNumberish],
    [string],
    "view"
  >;

  getProjectCount: TypedContractMethod<[], [bigint], "view">;

  getProjectInfo: TypedContractMethod<
    [projectId: BigNumberish],
    [[string, string] & { name: string; owner: string }],
    "view"
  >;

  getProjectTotal: TypedContractMethod<
    [projectId: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<
    [projectId: BigNumberish, inputAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDonationOf"
  ): TypedContractMethod<
    [projectId: BigNumberish, donor: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyDonation"
  ): TypedContractMethod<[projectId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getProjectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProjectInfo"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [[string, string] & { name: string; owner: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectTotal"
  ): TypedContractMethod<[projectId: BigNumberish], [string], "view">;

  getEvent(
    key: "Donated"
  ): TypedContractEvent<
    DonatedEvent.InputTuple,
    DonatedEvent.OutputTuple,
    DonatedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;

  filters: {
    "Donated(uint256,address)": TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;
    Donated: TypedContractEvent<
      DonatedEvent.InputTuple,
      DonatedEvent.OutputTuple,
      DonatedEvent.OutputObject
    >;

    "ProjectCreated(uint256,address,string)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
  };
}
